UPDATE discovery_search_queries
SET active = true
WHERE query = 'site:job-boards.greenhouse.io "software engineer" remote';

DELETE FROM discovery_search_queries WHERE query IN (
    'site:jobs.lever.co ("node.js" OR "nodejs" OR "node developer")',
    'site:boards.greenhouse.io ("node.js" OR "typescript" OR "javascript")',
    'site:jobs.ashbyhq.com ("node.js" OR "typescript")',
    'site:jobs.lever.co ("nestjs" OR "express.js" OR "fastify")',
    'site:boards.greenhouse.io "full stack" ("react" OR "next.js")',
    'site:jobs.ashbyhq.com ("next.js" OR "react" OR "typescript")',
    'site:jobs.lever.co ("python" OR "django" OR "fastapi")',
    'site:boards.greenhouse.io ("python" OR "django" OR "fastapi")',
    'site:jobs.ashbyhq.com ("python" OR "flask" OR "django")',
    'site:jobs.lever.co "machine learning" ("python" OR "pytorch")',
    'site:jobs.lever.co ("golang" OR "go engineer" OR "go developer")',
    'site:boards.greenhouse.io ("rust" OR "golang" OR "systems engineer")',
    'site:jobs.ashbyhq.com ("rust" OR "golang")',
    'site:jobs.lever.co ("c++" OR "cpp" OR "embedded")',
    'site:jobs.lever.co ("java" OR "kotlin" OR "spring boot")',
    'site:boards.greenhouse.io ("java engineer" OR "kotlin" OR "spring")',
    'site:jobs.ashbyhq.com ("java" OR "kotlin")',
    'site:boards.greenhouse.io ("scala" OR "spark" OR "kafka")',
    'site:jobs.lever.co (".net" OR "csharp" OR "C#")',
    'site:jobs.lever.co ("graphql" OR "api engineer" OR "backend")',
    'site:jobs.lever.co ("react" OR "frontend engineer" OR "frontend developer")',
    'site:boards.greenhouse.io ("react" OR "vue" OR "angular")',
    'site:jobs.ashbyhq.com ("frontend" OR "react" OR "vue")',
    'site:jobs.lever.co ("iOS" OR "Swift" OR "Android" OR "Kotlin")',
    'site:jobs.lever.co ("data engineer" OR "spark" OR "airflow")',
    'site:boards.greenhouse.io ("data engineer" OR "dbt" OR "snowflake")',
    'site:jobs.ashbyhq.com ("machine learning" OR "ML engineer" OR "LLM")',
    'site:jobs.lever.co ("kubernetes" OR "k8s" OR "terraform")',
    'site:boards.greenhouse.io ("devops" OR "SRE" OR "platform engineer")',
    'site:jobs.ashbyhq.com ("aws" OR "cloud engineer" OR "infrastructure")',
    'site:jobs.lever.co ("docker" OR "CI/CD" OR "GitOps")',
    'site:boards.greenhouse.io ("postgres" OR "postgresql" OR "mongodb")',
    'site:jobs.lever.co ("redis" OR "kafka" OR "postgresql")',
    'site:jobs.lever.co ("ruby" OR "rails" OR "ruby on rails")',
    'site:jobs.lever.co ("php" OR "laravel" OR "wordpress")',
    'site:boards.greenhouse.io ("security engineer" OR "application security")',
    'site:jobs.ashbyhq.com ("QA engineer" OR "SDET" OR "test automation")',
    'site:jobs.lever.co ("staff engineer" OR "principal engineer" OR "senior software")',
    'site:boards.greenhouse.io ("engineering manager" OR "tech lead")',
    'site:jobs.lever.co remote ("software engineer" OR "backend")',
    'site:boards.greenhouse.io remote ("software engineer" OR "backend engineer")',
    'site:jobs.ashbyhq.com remote ("typescript" OR "python" OR "go")'
);
